[package]
name = "quarm-monitor"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
quarm-config.workspace = true
quarm-audio.workspace = true

[dev-dependencies]
quarm-audio = { workspace = true, features = ["test-support"] }
